# Generated by Django 2.0.13 on 2019-08-20 11:57

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loadstatus',
            fields=[
                ('load_status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'LoadStatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=14)),
                ('nrc', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=100)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date_scheduled', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('driver_id', models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=models.SET(api.models.get_sentinel_driver), to='api.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Keypersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=200)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('tonnage', models.FloatField(null=True)),
                ('pick_up_date', models.DateField(null=True)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('additional_info', models.CharField(blank=True, max_length=200, null=True)),
                ('pick_up_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('drop_off_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('attachment', models.BinaryField(null=True)),
                ('staged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Loadtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_type', models.CharField(max_length=200)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'LoadType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=20)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('trailer_type', models.CharField(max_length=200)),
                ('tonnage', models.FloatField()),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('truck_make', models.CharField(max_length=200)),
                ('truck_type', models.CharField(max_length=200)),
                ('truck_model', models.CharField(max_length=200)),
                ('tonnage', models.FloatField()),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='load',
            name='drop_off_location',
            field=models.ForeignKey(blank=True, db_column='drop_off_location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drop_off', to='api.Location'),
        ),
        migrations.AddField(
            model_name='load',
            name='job_id',
            field=models.ForeignKey(blank=True, db_column='job_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Job'),
        ),
        migrations.AddField(
            model_name='load',
            name='load_type',
            field=models.ForeignKey(blank=True, db_column='load_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Loadtype'),
        ),
        migrations.AddField(
            model_name='load',
            name='pick_up_location',
            field=models.ForeignKey(blank=True, db_column='pick_up_location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_up', to='api.Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='trailer_id',
            field=models.ForeignKey(blank=True, db_column='trialer_id', null=True, on_delete=models.SET(api.models.get_sentinel_trailer), to='api.Trailer'),
        ),
        migrations.AddField(
            model_name='job',
            name='truck_id',
            field=models.ForeignKey(blank=True, db_column='truck_id', null=True, on_delete=models.SET(api.models.get_sentinel_truck), to='api.Truck'),
        ),
    ]
